
#ifndef IQD_CONFIG_H_
#define IQD_CONFIG_H_

#include "WAXM_config.h"


#define IQD_HAVE_CLOCK_GETTIME 	WAXM_HAVE_CLOCK_GETTIME
#define IQD_HAVE_ASL 			WAXM_HAVE_ASL
#define IQD_HAVE_LAPACK 		WAXM_HAVE_LAPACK
#define IQD_HAVE_CSDP 			WAXM_HAVE_CSDP
#define IQD_HAVE_CPLEX 			WAXM_HAVE_CPLEX
#define IQD_HAVE_IPOPT 			WAXM_HAVE_IPOPT
#define IQD_HAVE_BONMIN 		WAXM_HAVE_BONMIN
#define IQD_HAVE_MURIQUI 		WAXM_HAVE_MURIQUI
#define IQD_HAVE_MOSEK 			WAXM_HAVE_MOSEK
#define IQD_HAVE_GUROBI 		WAXM_HAVE_GUROBI


#endif
    